// packages/react/src/Charts.tsx
import {
  useEffect,
  useId,
  useRef,
  useState,
  type MouseEvent as ReactMouseEvent,
  type ReactNode,
} from 'react';
import { Icon } from '@vespera-ui/icons';

type Pt = [number, number];

/** Smooth (cubic) SVG path through a list of points. */
export function smoothPath(pts: Pt[]): string {
  if (pts.length < 2) return '';
  let d = `M ${pts[0]![0]} ${pts[0]![1]}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const [x0, y0] = pts[i]!;
    const [x1, y1] = pts[i + 1]!;
    const cx = (x0 + x1) / 2;
    d += ` C ${cx} ${y0} ${cx} ${y1} ${x1} ${y1}`;
  }
  return d;
}

/** Compact number formatting: 1500 → "1.5k", 2_000_000 → "2M". */
export function niceNum(n: number): string {
  if (Math.abs(n) >= 1e6) return (n / 1e6).toFixed(n % 1e6 === 0 ? 0 : 1) + 'M';
  if (Math.abs(n) >= 1e3) return (n / 1e3).toFixed(n % 1e3 === 0 ? 0 : 1) + 'k';
  return String(n);
}

function useWidth(initial: number) {
  const ref = useRef<HTMLDivElement>(null);
  const [w, setW] = useState(initial);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const ro = new ResizeObserver((entries) => {
      const e = entries[0];
      if (e) setW(e.contentRect.width);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);
  return [ref, w] as const;
}

export interface SparklineProps {
  data: number[];
  color?: string;
  w?: number;
  h?: number;
  fill?: boolean;
}

export function Sparkline({
  data,
  color = 'var(--accent)',
  w = 110,
  h = 34,
  fill = true,
}: SparklineProps) {
  const gid = 'spk' + useId().replace(/:/g, '');
  const min = Math.min(...data);
  const max = Math.max(...data);
  const rng = max - min || 1;
  const pts: Pt[] = data.map((v, i) => [
    (i / (data.length - 1)) * w,
    h - 3 - ((v - min) / rng) * (h - 6),
  ]);
  const d = smoothPath(pts);
  const last = pts[pts.length - 1] ?? [0, 0];
  return (
    <svg
      width={w}
      height={h}
      viewBox={`0 0 ${w} ${h}`}
      style={{ display: 'block', overflow: 'visible' }}
    >
      {fill && (
        <>
          <defs>
            <linearGradient id={gid} x1="0" x2="0" y1="0" y2="1">
              <stop offset="0" stopColor={color} stopOpacity="0.28" />
              <stop offset="1" stopColor={color} stopOpacity="0" />
            </linearGradient>
          </defs>
          <path d={`${d} L ${w} ${h} L 0 ${h} Z`} fill={`url(#${gid})`} />
        </>
      )}
      <path d={d} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" />
      <circle cx={last[0]} cy={last[1]} r="2.6" fill={color} />
    </svg>
  );
}

export interface AreaChartProps {
  /** One series (`[data]`) or two when `dual`. */
  series: number[][];
  labels?: string[];
  height?: number;
  color?: string;
  color2?: string;
  dual?: boolean;
}

export function AreaChart({
  series,
  labels,
  height = 260,
  color = 'var(--accent)',
  color2 = 'var(--accent-2)',
  dual = false,
}: AreaChartProps) {
  const [wrapRef, w] = useWidth(760);
  const [hover, setHover] = useState<number | null>(null);
  const gid = 'ac' + useId().replace(/:/g, '');

  const padL = 38;
  const padB = 26;
  const padT = 12;
  const padR = 8;
  const innerW = Math.max(10, w - padL - padR);
  const innerH = height - padB - padT;
  const s0 = series[0] ?? [];
  const s1 = series[1];
  const all = dual && s1 ? [...s0, ...s1] : s0;
  const max = Math.max(...all, 0) * 1.12;
  const rng = max || 1;
  const sx = (i: number, len: number) => padL + (i / Math.max(1, len - 1)) * innerW;
  const sy = (v: number) => padT + innerH - (v / rng) * innerH;
  const mkPts = (arr: number[]): Pt[] => arr.map((v, i) => [sx(i, arr.length), sy(v)]);
  const lines: Pt[][] = (dual && s1 ? [s0, s1] : [s0]).map(mkPts);
  const yTicks = 4;

  const onMove = (e: ReactMouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const i = Math.round(((e.clientX - rect.left - padL) / innerW) * (s0.length - 1));
    if (i >= 0 && i < s0.length) setHover(i);
  };

  return (
    <div
      ref={wrapRef}
      style={{ position: 'relative' }}
      onMouseMove={onMove}
      onMouseLeave={() => setHover(null)}
    >
      <svg width={w} height={height} style={{ display: 'block' }}>
        <defs>
          <linearGradient id={gid} x1="0" x2="0" y1="0" y2="1">
            <stop offset="0" stopColor={color} stopOpacity="0.22" />
            <stop offset="1" stopColor={color} stopOpacity="0" />
          </linearGradient>
        </defs>
        {Array.from({ length: yTicks + 1 }).map((_, i) => {
          const y = sy((max / yTicks) * i);
          return (
            <g key={i}>
              <line
                x1={padL}
                x2={w - padR}
                y1={y}
                y2={y}
                stroke="var(--grid-line)"
                strokeWidth="1"
              />
              <text
                x={padL - 8}
                y={y + 3.5}
                textAnchor="end"
                fontSize="10"
                fill="var(--text-faint)"
                fontFamily="var(--font-mono)"
              >
                {niceNum(Math.round((max / yTicks) * i))}
              </text>
            </g>
          );
        })}
        {labels?.map((lb, i) =>
          i % Math.ceil(labels.length / 7) === 0 ? (
            <text
              key={i}
              x={sx(i, labels.length)}
              y={height - 8}
              textAnchor="middle"
              fontSize="10"
              fill="var(--text-faint)"
              fontFamily="var(--font-mono)"
            >
              {lb}
            </text>
          ) : null,
        )}
        {lines.map((pts, li) => {
          const stroke = li === 0 ? color : color2;
          const lastPt = pts[pts.length - 1];
          const firstPt = pts[0];
          return (
            <g key={li}>
              {li === 0 && firstPt && lastPt && (
                <path
                  d={`${smoothPath(pts)} L ${lastPt[0]} ${padT + innerH} L ${firstPt[0]} ${padT + innerH} Z`}
                  fill={`url(#${gid})`}
                />
              )}
              <path
                d={smoothPath(pts)}
                fill="none"
                stroke={stroke}
                strokeWidth="2.4"
                strokeLinecap="round"
                strokeDasharray={li === 1 ? '5 5' : undefined}
                style={{ opacity: li === 1 ? 0.7 : 1 }}
              />
            </g>
          );
        })}
        {hover != null && (
          <>
            <line
              x1={sx(hover, s0.length)}
              x2={sx(hover, s0.length)}
              y1={padT}
              y2={padT + innerH}
              stroke="var(--border-strong)"
              strokeWidth="1"
            />
            {lines.map((pts, li) => {
              const p = pts[hover];
              return p ? (
                <circle
                  key={li}
                  cx={p[0]}
                  cy={p[1]}
                  r="4"
                  fill="var(--surface-1)"
                  stroke={li === 0 ? color : color2}
                  strokeWidth="2.5"
                />
              ) : null;
            })}
          </>
        )}
      </svg>
      {hover != null && (
        <div
          style={{
            position: 'absolute',
            left: Math.min(sx(hover, s0.length) + 10, w - 130),
            top: 8,
            background: 'var(--surface-3)',
            border: '1px solid var(--border-strong)',
            borderRadius: 8,
            padding: '7px 10px',
            pointerEvents: 'none',
            boxShadow: 'var(--shadow)',
            fontSize: 11.5,
          }}
        >
          <div className="eyebrow" style={{ marginBottom: 3 }}>
            {labels ? labels[hover] : `#${hover}`}
          </div>
          <div style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
            {niceNum(s0[hover] ?? 0)}
          </div>
        </div>
      )}
    </div>
  );
}

export interface BarChartProps {
  data: number[];
  labels?: string[];
  height?: number;
  color?: string;
}

export function BarChart({ data, labels, height = 240, color = 'var(--accent)' }: BarChartProps) {
  const [wrapRef, w] = useWidth(620);
  const [hover, setHover] = useState<number | null>(null);
  const padL = 34;
  const padB = 26;
  const padT = 10;
  const innerW = Math.max(10, w - padL - 8);
  const innerH = height - padB - padT;
  const max = Math.max(...data, 0) * 1.15 || 1;
  const bw = innerW / data.length;
  return (
    <div ref={wrapRef}>
      <svg width={w} height={height} style={{ display: 'block' }}>
        {[0, 0.5, 1].map((f, i) => {
          const y = padT + innerH - f * innerH;
          return (
            <g key={i}>
              <line x1={padL} x2={w - 8} y1={y} y2={y} stroke="var(--grid-line)" />
              <text
                x={padL - 8}
                y={y + 3.5}
                textAnchor="end"
                fontSize="10"
                fill="var(--text-faint)"
                fontFamily="var(--font-mono)"
              >
                {niceNum(Math.round(max * f))}
              </text>
            </g>
          );
        })}
        {data.map((v, i) => {
          const bh = (v / max) * innerH;
          const x = padL + i * bw + bw * 0.18;
          const bwi = bw * 0.64;
          const active = hover === i;
          return (
            <g key={i} onMouseEnter={() => setHover(i)} onMouseLeave={() => setHover(null)}>
              <rect x={padL + i * bw} y={padT} width={bw} height={innerH} fill="transparent" />
              <rect
                x={x}
                y={padT + innerH - bh}
                width={bwi}
                height={bh}
                rx="4"
                fill={active ? color : `color-mix(in oklab, ${color} 78%, transparent)`}
                style={{ transition: 'fill .15s' }}
              />
              {labels?.[i] != null && (
                <text
                  x={x + bwi / 2}
                  y={height - 8}
                  textAnchor="middle"
                  fontSize="10"
                  fill="var(--text-faint)"
                  fontFamily="var(--font-mono)"
                >
                  {labels[i]}
                </text>
              )}
            </g>
          );
        })}
      </svg>
    </div>
  );
}

export interface DonutDatum {
  label: ReactNode;
  value: number;
  color: string;
}

export interface DonutProps {
  data: DonutDatum[];
  size?: number;
  thickness?: number;
  /** Content rendered in the hole (e.g. a total). */
  centerLabel?: ReactNode;
}

export function Donut({ data, size = 168, thickness = 22, centerLabel }: DonutProps) {
  const total = data.reduce((s, d) => s + d.value, 0) || 1;
  const r = (size - thickness) / 2;
  const c = size / 2;
  const circ = 2 * Math.PI * r;
  let acc = 0;
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 22 }}>
      <div style={{ position: 'relative', width: size, height: size, flexShrink: 0 }}>
        {centerLabel != null && (
          <div
            style={{
              position: 'absolute',
              inset: 0,
              display: 'grid',
              placeItems: 'center',
              textAlign: 'center',
            }}
          >
            {centerLabel}
          </div>
        )}
        <svg width={size} height={size} style={{ transform: 'rotate(-90deg)', display: 'block' }}>
          <circle
            cx={c}
            cy={c}
            r={r}
            fill="none"
            stroke="var(--surface-3)"
            strokeWidth={thickness}
          />
          {data.map((d, i) => {
            const len = (d.value / total) * circ;
            const seg = (
              <circle
                key={i}
                cx={c}
                cy={c}
                r={r}
                fill="none"
                stroke={d.color}
                strokeWidth={thickness}
                strokeDasharray={`${len - 2.5} ${circ - len + 2.5}`}
                strokeDashoffset={-acc}
                strokeLinecap="round"
              />
            );
            acc += len;
            return seg;
          })}
        </svg>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 9, flex: 1 }}>
        {data.map((d, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 9, fontSize: 12.5 }}>
            <i
              style={{ width: 9, height: 9, borderRadius: 3, background: d.color, flexShrink: 0 }}
            />
            <span style={{ color: 'var(--text-dim)', flex: 1 }}>{d.label}</span>
            <span className="mono tnum" style={{ fontWeight: 600 }}>
              {Math.round((d.value / total) * 100)}%
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export interface StatCardProps {
  icon?: ReactNode;
  label?: ReactNode;
  value?: ReactNode;
  delta?: ReactNode;
  deltaDir?: 'up' | 'down';
  spark?: number[];
  sparkColor?: string;
}

export function StatCard({
  icon,
  label,
  value,
  delta,
  deltaDir = 'up',
  spark,
  sparkColor,
}: StatCardProps) {
  const Arrow = deltaDir === 'up' ? Icon.arrowUp : Icon.arrowDown;
  return (
    <div
      className="card card-pad vsp-rise"
      style={{ display: 'flex', flexDirection: 'column', gap: 14 }}
    >
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span
            style={{
              width: 34,
              height: 34,
              borderRadius: 'var(--r-sm)',
              display: 'grid',
              placeItems: 'center',
              background: 'color-mix(in oklab, var(--accent) 13%, transparent)',
              color: 'var(--accent)',
            }}
          >
            {icon}
          </span>
          <span className="eyebrow">{label}</span>
        </div>
        {delta != null && (
          <span className={`badge ${deltaDir === 'up' ? 'badge-pos' : 'badge-neg'}`}>
            <Arrow style={{ width: 11, height: 11 }} />
            {delta}
          </span>
        )}
      </div>
      <div
        style={{
          display: 'flex',
          alignItems: 'flex-end',
          justifyContent: 'space-between',
          gap: 12,
        }}
      >
        <div
          className="tnum"
          style={{ fontSize: 30, fontWeight: 800, letterSpacing: '-.02em', lineHeight: 1 }}
        >
          {value}
        </div>
        {spark && <Sparkline data={spark} color={sparkColor ?? 'var(--accent)'} />}
      </div>
    </div>
  );
}

// packages/angular/src/charts.component.ts
import { Component, Input } from '@angular/core';

function niceNum(n: number): string {
  if (Math.abs(n) >= 1e6) return (n / 1e6).toFixed(n % 1e6 === 0 ? 0 : 1) + 'M';
  if (Math.abs(n) >= 1e3) return (n / 1e3).toFixed(n % 1e3 === 0 ? 0 : 1) + 'k';
  return String(n);
}

type Pt = [number, number];
function smoothPath(pts: Pt[]): string {
  if (pts.length < 2) return '';
  let d = `M ${pts[0]![0]} ${pts[0]![1]}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const [x0, y0] = pts[i]!;
    const [x1, y1] = pts[i + 1]!;
    const cx = (x0 + x1) / 2;
    d += ` C ${cx} ${y0} ${cx} ${y1} ${x1} ${y1}`;
  }
  return d;
}

let sparkUid = 0;

@Component({
  selector: 'vsp-sparkline',
  template: `<svg
    [attr.width]="w"
    [attr.height]="h"
    [attr.viewBox]="'0 0 ' + w + ' ' + h"
    style="display: block; overflow: visible"
  >
    @if (fill) {
      <defs>
        <linearGradient [id]="gid" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0" [attr.stop-color]="color" stop-opacity="0.28" />
          <stop offset="1" [attr.stop-color]="color" stop-opacity="0" />
        </linearGradient>
      </defs>
      <path [attr.d]="areaD" [attr.fill]="'url(#' + gid + ')'" />
    }
    <path [attr.d]="d" fill="none" [attr.stroke]="color" stroke-width="2" stroke-linecap="round" />
    <circle [attr.cx]="last[0]" [attr.cy]="last[1]" r="2.6" [attr.fill]="color" />
  </svg>`,
})
export class VspSparkline {
  @Input() data: number[] = [];
  @Input() color = 'var(--accent)';
  @Input() w = 110;
  @Input() h = 34;
  @Input() fill = true;
  gid = 'spk' + ++sparkUid;
  get pts(): Pt[] {
    const min = Math.min(...this.data);
    const max = Math.max(...this.data);
    const rng = max - min || 1;
    return this.data.map((v, i) => [
      (i / (this.data.length - 1)) * this.w,
      this.h - 3 - ((v - min) / rng) * (this.h - 6),
    ]);
  }
  get d(): string {
    return smoothPath(this.pts);
  }
  get areaD(): string {
    return `${this.d} L ${this.w} ${this.h} L 0 ${this.h} Z`;
  }
  get last(): Pt {
    return this.pts[this.pts.length - 1] ?? [0, 0];
  }
}

export interface DonutDatum {
  label: string;
  value: number;
  color: string;
}

@Component({
  selector: 'vsp-donut',
  template: `<div style="display: flex; align-items: center; gap: 22px">
    <div
      [style.width.px]="size"
      [style.height.px]="size"
      style="position: relative; flex-shrink: 0"
    >
      @if (hover != null) {
        <div
          style="position: absolute; inset: 0; display: grid; place-items: center; text-align: center"
        >
          <div>
            <div style="font-size: 19px; font-weight: 800; letter-spacing: -0.02em">
              {{ fmt(data[hover].value) }}
            </div>
            <div style="font-size: 11px; color: var(--text-dim); margin-top: 2px">
              {{ data[hover].label }}
            </div>
          </div>
        </div>
      } @else if (centerLabel != null) {
        <div
          style="position: absolute; inset: 0; display: grid; place-items: center; text-align: center"
        >
          {{ centerLabel }}
        </div>
      }
      <svg
        [attr.width]="size"
        [attr.height]="size"
        style="transform: rotate(-90deg); display: block"
      >
        <circle
          [attr.cx]="c"
          [attr.cy]="c"
          [attr.r]="r"
          fill="none"
          stroke="var(--surface-3)"
          [attr.stroke-width]="thickness"
        />
        @for (s of segs; track $index; let i = $index) {
          <circle
            [attr.cx]="c"
            [attr.cy]="c"
            [attr.r]="r"
            fill="none"
            [attr.stroke]="s.color"
            [attr.stroke-width]="thickness"
            [attr.stroke-dasharray]="s.dash"
            [attr.stroke-dashoffset]="s.offset"
            stroke-linecap="round"
            [attr.opacity]="hover === null || hover === i ? 1 : 0.3"
            style="transition: opacity 0.15s; cursor: pointer"
            (mouseenter)="hover = i"
            (mouseleave)="hover = null"
          />
        }
      </svg>
    </div>
    <div style="display: flex; flex-direction: column; gap: 9px; flex: 1">
      @for (d of data; track $index; let i = $index) {
        <div
          style="display: flex; align-items: center; gap: 9px; font-size: 12.5px; cursor: pointer; transition: opacity 0.15s"
          [style.opacity]="hover === null || hover === i ? 1 : 0.45"
          (mouseenter)="hover = i"
          (mouseleave)="hover = null"
        >
          <i
            [style.background]="d.color"
            style="width: 9px; height: 9px; border-radius: 3px; flex-shrink: 0"
          ></i>
          <span style="color: var(--text-dim); flex: 1">{{ d.label }}</span>
          <span class="mono tnum" style="font-weight: 600">{{ pct(d.value) }}%</span>
        </div>
      }
    </div>
  </div>`,
})
export class VspDonut {
  @Input() data: DonutDatum[] = [];
  @Input() size = 168;
  @Input() thickness = 22;
  @Input() centerLabel?: string;
  @Input() valueFormat?: (n: number) => string;
  hover: number | null = null;
  fmt(n: number): string {
    return this.valueFormat ? this.valueFormat(n) : niceNum(n);
  }
  get total(): number {
    return this.data.reduce((s, d) => s + d.value, 0) || 1;
  }
  get r(): number {
    return (this.size - this.thickness) / 2;
  }
  get c(): number {
    return this.size / 2;
  }
  get circ(): number {
    return 2 * Math.PI * this.r;
  }
  get segs(): { color: string; dash: string; offset: number }[] {
    let acc = 0;
    return this.data.map((d) => {
      const len = (d.value / this.total) * this.circ;
      const seg = { color: d.color, dash: `${len - 2.5} ${this.circ - len + 2.5}`, offset: -acc };
      acc += len;
      return seg;
    });
  }
  pct(v: number): number {
    return Math.round((v / this.total) * 100);
  }
}

@Component({
  selector: 'vsp-stat-card',
  imports: [VspSparkline],
  template: `<div
    class="card card-pad vsp-rise"
    style="display: flex; flex-direction: column; gap: 14px"
  >
    <div style="display: flex; align-items: center; justify-content: space-between">
      <div style="display: flex; align-items: center; gap: 10px">
        <span
          style="width: 34px; height: 34px; border-radius: var(--r-sm); display: grid; place-items: center; background: color-mix(in oklab, var(--accent) 13%, transparent); color: var(--accent)"
        >
          <ng-content select="[slot=icon]" />
        </span>
        <span class="eyebrow">{{ label }}</span>
      </div>
      @if (delta != null) {
        <span [class]="deltaCls">
          <svg
            viewBox="0 0 24 24"
            width="11"
            height="11"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path [attr.d]="arrow" />
          </svg>
          {{ delta }}
        </span>
      }
    </div>
    <div style="display: flex; align-items: flex-end; justify-content: space-between; gap: 12px">
      <div
        class="tnum"
        style="font-size: 30px; font-weight: 800; letter-spacing: -0.02em; line-height: 1"
      >
        {{ value }}
      </div>
      @if (spark) {
        <vsp-sparkline [data]="spark" [color]="sparkColor" />
      }
    </div>
  </div>`,
})
export class VspStatCard {
  @Input() label?: string;
  @Input() value?: string;
  @Input() delta?: string;
  @Input() deltaDir: 'up' | 'down' = 'up';
  @Input() spark?: number[];
  @Input() sparkColor = 'var(--accent)';
  get deltaCls(): string {
    return 'badge ' + (this.deltaDir === 'up' ? 'badge-pos' : 'badge-neg');
  }
  get arrow(): string {
    return this.deltaDir === 'up' ? 'M12 19V5M5 12l7-7 7 7' : 'M12 5v14M5 12l7 7 7-7';
  }
}
