// packages/react/src/Feedback.tsx
import type { CSSProperties } from 'react';
import { cx } from './cx';

export interface ProgressProps {
  value?: number;
  /** Bar color (defaults to the accent). */
  tone?: string;
  height?: number;
  /** Upper bound for `value` (default 100). */
  max?: number;
  /** Unknown-duration loading — animates continuously, ignores `value`. */
  indeterminate?: boolean;
  /** Accessible label for the progress bar. */
  label?: string;
}

export function Progress({
  value = 0,
  tone,
  height = 6,
  max = 100,
  indeterminate,
  label,
}: ProgressProps) {
  const pct = Math.min(100, Math.max(0, (value / max) * 100));
  return (
    <div
      className={cx('meter', indeterminate && 'indeterminate')}
      style={{ height }}
      role="progressbar"
      aria-label={label}
      aria-valuemin={indeterminate ? undefined : 0}
      aria-valuemax={indeterminate ? undefined : max}
      aria-valuenow={indeterminate ? undefined : value}
    >
      <i
        style={
          indeterminate
            ? { background: tone }
            : { width: `${pct}%`, background: tone, transition: 'width .3s' }
        }
      />
    </div>
  );
}

export interface SkeletonProps {
  w?: number | string;
  h?: number | string;
  r?: number | string;
  style?: CSSProperties;
}

export function Skeleton({ w = '100%', h = 12, r = 7, style }: SkeletonProps) {
  return <div className="skel" style={{ width: w, height: h, borderRadius: r, ...style }} />;
}

export interface SpinnerProps {
  size?: 'lg';
  className?: string;
}

export function Spinner({ size, className }: SpinnerProps) {
  return <span className={cx('ui-spinner', size === 'lg' && 'lg', className)} aria-hidden />;
}

// packages/angular/src/feedback.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'vsp-spinner',
  template: `<span [class]="cls" aria-hidden="true"></span>`,
})
export class VspSpinner {
  @Input() size?: 'lg';
  get cls(): string {
    return this.size === 'lg' ? 'ui-spinner lg' : 'ui-spinner';
  }
}

@Component({
  selector: 'vsp-icon-button',
  template: `<button type="button" class="vsp-icon-btn" [attr.aria-label]="label">
    <ng-content />
  </button>`,
})
export class VspIconButton {
  @Input() label?: string;
}

@Component({
  selector: 'vsp-progress',
  template: `<div
    [class]="indeterminate ? 'meter indeterminate' : 'meter'"
    [style.height.px]="height"
    role="progressbar"
    [attr.aria-label]="label"
    [attr.aria-valuemin]="indeterminate ? null : 0"
    [attr.aria-valuemax]="indeterminate ? null : max"
    [attr.aria-valuenow]="indeterminate ? null : value"
  >
    @if (indeterminate) {
      <i [style.background]="tone"></i>
    } @else {
      <i [style.width.%]="pct" [style.background]="tone" style="transition: width 0.3s"></i>
    }
  </div>`,
})
export class VspProgress {
  @Input() value = 0;
  @Input() tone?: string;
  @Input() height = 6;
  @Input() max = 100;
  @Input() indeterminate = false;
  @Input() label?: string;
  get pct(): number {
    return Math.min(100, Math.max(0, (this.value / this.max) * 100));
  }
}

@Component({
  selector: 'vsp-skeleton',
  template: `<div
    class="skel"
    [style.width]="px(w)"
    [style.height]="px(h)"
    [style.borderRadius]="px(r)"
  ></div>`,
})
export class VspSkeleton {
  @Input() w: string | number = '100%';
  @Input() h: string | number = 12;
  @Input() r: number = 7;
  px(v: string | number): string {
    return typeof v === 'number' ? `${v}px` : v;
  }
}
