// packages/react/src/Select.tsx
import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type Dispatch,
  type KeyboardEvent as ReactKeyboardEvent,
  type ReactNode,
  type RefObject,
  type SetStateAction,
} from 'react';
import { createPortal } from 'react-dom';
import { Icon } from '@vespera-ui/icons';
import { getPortalTarget } from './portal';
import { cx } from './cx';

export type SelectValue = string | number;

export interface SelectOption {
  value: SelectValue;
  label: string;
  /** Optional color swatch shown before the label. */
  swatch?: string;
}

export type SelectOptionInput = SelectValue | SelectOption;

function normalizeOption(o: SelectOptionInput): SelectOption {
  return typeof o === 'object' ? o : { value: o, label: String(o) };
}

/* ---------------- anchored dropdown panel ---------------- */

interface SelPanelProps {
  open: boolean;
  anchorRef: RefObject<HTMLElement | null>;
  onClose: () => void;
  width?: number;
  children?: ReactNode;
}

function SelPanel({ open, anchorRef, onClose, width, children }: SelPanelProps) {
  const [rect, setRect] = useState<DOMRect | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  useLayoutEffect(() => {
    if (open && anchorRef.current) setRect(anchorRef.current.getBoundingClientRect());
  }, [open, anchorRef]);

  useEffect(() => {
    if (!open) return;
    const reposition = () => {
      if (anchorRef.current) setRect(anchorRef.current.getBoundingClientRect());
    };
    const onDoc = (e: MouseEvent) => {
      const t = e.target as Node;
      if (!ref.current?.contains(t) && !anchorRef.current?.contains(t)) onClose();
    };
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('mousedown', onDoc);
    window.addEventListener('keydown', onEsc);
    window.addEventListener('resize', reposition);
    window.addEventListener('scroll', reposition, true);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      window.removeEventListener('keydown', onEsc);
      window.removeEventListener('resize', reposition);
      window.removeEventListener('scroll', reposition, true);
    };
  }, [open, anchorRef, onClose]);

  if (!open || !rect) return null;
  const target = getPortalTarget();
  if (!target) return null;

  const maxBelow = window.innerHeight - rect.bottom - 16;
  return createPortal(
    <div
      ref={ref}
      className="ui-menu ui-combo"
      style={{
        position: 'fixed',
        top: rect.bottom + 6,
        left: rect.left,
        width: width ?? rect.width,
        zIndex: 330,
        maxHeight: Math.max(220, maxBelow),
      }}
    >
      {children}
    </div>,
    target,
  );
}

/* ---------------- search + list ---------------- */

interface ComboListProps {
  q: string;
  setQ: (q: string) => void;
  items: SelectOption[];
  onPick: (o: SelectOption) => void;
  activeIdx: number;
  setActiveIdx: Dispatch<SetStateAction<number>>;
  isSel: (o: SelectOption) => boolean;
  searchPlaceholder?: string;
  footer?: ReactNode;
}

function ComboList({
  q,
  setQ,
  items,
  onPick,
  activeIdx,
  setActiveIdx,
  isSel,
  searchPlaceholder,
  footer,
}: ComboListProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => {
    const id = window.setTimeout(() => inputRef.current?.focus(), 30);
    return () => window.clearTimeout(id);
  }, []);

  const onKey = (e: ReactKeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setActiveIdx((i) => Math.min(items.length - 1, i + 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setActiveIdx((i) => Math.max(0, i - 1));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const it = items[activeIdx];
      if (it) onPick(it);
    }
  };

  return (
    <>
      <div className="ui-combo-search">
        <Icon.search />
        <input
          ref={inputRef}
          value={q}
          placeholder={searchPlaceholder ?? 'Search…'}
          onChange={(e) => {
            setQ(e.target.value);
            setActiveIdx(0);
          }}
          onKeyDown={onKey}
        />
      </div>
      <div className="ui-combo-list">
        {items.length === 0 && <div className="ui-combo-empty">No matches for “{q}”</div>}
        {items.map((o, i) => (
          <div
            key={String(o.value)}
            className={cx('ui-combo-item', i === activeIdx && 'active')}
            onMouseEnter={() => setActiveIdx(i)}
            onClick={() => onPick(o)}
          >
            {o.swatch && (
              <span
                style={{
                  width: 9,
                  height: 9,
                  borderRadius: 3,
                  background: o.swatch,
                  flexShrink: 0,
                }}
              />
            )}
            <span>{o.label}</span>
            {isSel(o) && <Icon.check className="tick" />}
          </div>
        ))}
      </div>
      {footer}
    </>
  );
}

/* ---------------- Select (themed drop-in, auto-searches at ≥8 options) ---------------- */

export interface SelectProps {
  options: SelectOptionInput[];
  value?: SelectValue;
  defaultValue?: SelectValue;
  onChange?: (value: SelectValue) => void;
  placeholder?: string;
  className?: string;
  style?: CSSProperties;
  disabled?: boolean;
  /** Force the search box on/off (defaults to on at ≥8 options). */
  searchable?: boolean;
}

export function Select({
  options,
  value,
  defaultValue,
  onChange,
  placeholder = 'Select…',
  className,
  style,
  disabled,
  searchable,
}: SelectProps) {
  const opts = options.map(normalizeOption);
  const controlled = value !== undefined;
  const [internal, setInternal] = useState<SelectValue | undefined>(defaultValue);
  const cur = controlled ? value : (internal ?? opts[0]?.value);
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const [active, setActive] = useState(0);
  const anchor = useRef<HTMLButtonElement>(null);

  const sel = opts.find((o) => String(o.value) === String(cur));
  const useSearch = searchable ?? opts.length >= 8;
  const items = useSearch
    ? opts.filter((o) => o.label.toLowerCase().includes(q.toLowerCase()))
    : opts;

  const choose = (o: SelectOption) => {
    if (!controlled) setInternal(o.value);
    onChange?.(o.value);
    setOpen(false);
    setQ('');
  };

  return (
    <>
      <button
        type="button"
        ref={anchor}
        disabled={disabled}
        className={cx('ui-selectbtn', open && 'open', className)}
        style={style}
        onClick={() => setOpen((o) => !o)}
      >
        <span className={cx('val', !sel && 'ph')}>{sel ? sel.label : placeholder}</span>
      </button>
      <SelPanel open={open} anchorRef={anchor} onClose={() => setOpen(false)}>
        {useSearch ? (
          <ComboList
            q={q}
            setQ={setQ}
            items={items}
            activeIdx={active}
            setActiveIdx={setActive}
            onPick={choose}
            isSel={(o) => String(o.value) === String(cur)}
          />
        ) : (
          <div className="ui-combo-list">
            {items.length === 0 ? (
              <div className="ui-combo-empty">No options</div>
            ) : (
              items.map((o) => (
                <div
                  key={String(o.value)}
                  className={cx('ui-combo-item', String(o.value) === String(cur) && 'active')}
                  onClick={() => choose(o)}
                >
                  {o.swatch && (
                    <span
                      style={{
                        width: 9,
                        height: 9,
                        borderRadius: 3,
                        background: o.swatch,
                        flexShrink: 0,
                      }}
                    />
                  )}
                  <span>{o.label}</span>
                  {String(o.value) === String(cur) && <Icon.check className="tick" />}
                </div>
              ))
            )}
          </div>
        )}
      </SelPanel>
    </>
  );
}

/* ---------------- Combobox (searchable single select) ---------------- */

export interface ComboboxProps {
  options: SelectOptionInput[];
  value?: SelectValue | null;
  onChange?: (value: SelectValue | null) => void;
  placeholder?: string;
  searchPlaceholder?: string;
  clearable?: boolean;
}

export function Combobox({
  options,
  value,
  onChange,
  placeholder = 'Select…',
  searchPlaceholder,
  clearable,
}: ComboboxProps) {
  const opts = options.map(normalizeOption);
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const [active, setActive] = useState(0);
  const anchor = useRef<HTMLButtonElement>(null);

  const sel = opts.find((o) => o.value === value);
  const items = opts.filter((o) => o.label.toLowerCase().includes(q.toLowerCase()));
  const pick = (o: SelectOption) => {
    onChange?.(o.value);
    setOpen(false);
    setQ('');
  };

  return (
    <>
      <button
        type="button"
        ref={anchor}
        className={cx('ui-trigger', open && 'open')}
        onClick={() => setOpen((o) => !o)}
      >
        <span className={cx('val', !sel && 'ph')}>{sel ? sel.label : placeholder}</span>
        {clearable && sel && (
          <span
            onClick={(e) => {
              e.stopPropagation();
              onChange?.(null);
            }}
            style={{ display: 'grid', placeItems: 'center', color: 'var(--text-faint)' }}
          >
            <Icon.x style={{ width: 14, height: 14 }} />
          </span>
        )}
        <Icon.chevDown className="chev" />
      </button>
      <SelPanel open={open} anchorRef={anchor} onClose={() => setOpen(false)}>
        <ComboList
          q={q}
          setQ={setQ}
          items={items}
          activeIdx={active}
          setActiveIdx={setActive}
          onPick={pick}
          isSel={(o) => o.value === value}
          searchPlaceholder={searchPlaceholder}
        />
      </SelPanel>
    </>
  );
}

/* ---------------- MultiSelect (searchable, tagged) ---------------- */

export interface MultiSelectProps {
  options: SelectOptionInput[];
  value?: SelectValue[];
  onChange?: (value: SelectValue[]) => void;
  placeholder?: string;
  searchPlaceholder?: string;
  max?: number;
}

export function MultiSelect({
  options,
  value = [],
  onChange,
  placeholder = 'Select…',
  searchPlaceholder,
  max,
}: MultiSelectProps) {
  const opts = options.map(normalizeOption);
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const [active, setActive] = useState(0);
  const anchor = useRef<HTMLDivElement>(null);

  const items = opts.filter((o) => o.label.toLowerCase().includes(q.toLowerCase()));
  const has = (v: SelectValue) => value.includes(v);
  const toggle = (o: SelectOption) => {
    if (has(o.value)) onChange?.(value.filter((v) => v !== o.value));
    else if (!max || value.length < max) onChange?.([...value, o.value]);
  };
  const selOpts = opts.filter((o) => has(o.value));

  return (
    <>
      <div
        role="button"
        tabIndex={0}
        ref={anchor}
        className={cx('ui-trigger', open && 'open')}
        onClick={() => setOpen((o) => !o)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            setOpen((o) => !o);
          }
        }}
        style={{ minHeight: 'var(--ctrl-h)' }}
      >
        {selOpts.length === 0 ? (
          <span className="val ph">{placeholder}</span>
        ) : (
          <span className="tags">
            {selOpts.map((o) => (
              <span key={String(o.value)} className="ui-tag" onClick={(e) => e.stopPropagation()}>
                {o.label}
                <button
                  type="button"
                  onClick={() => onChange?.(value.filter((v) => v !== o.value))}
                  aria-label={`Remove ${o.label}`}
                >
                  <Icon.x style={{ width: 11, height: 11 }} />
                </button>
              </span>
            ))}
          </span>
        )}
        <Icon.chevDown className="chev" />
      </div>
      <SelPanel open={open} anchorRef={anchor} onClose={() => setOpen(false)}>
        <ComboList
          q={q}
          setQ={setQ}
          items={items}
          activeIdx={active}
          setActiveIdx={setActive}
          onPick={toggle}
          isSel={(o) => has(o.value)}
          searchPlaceholder={searchPlaceholder}
          footer={
            <div className="ui-combo-foot">
              <span className="mono" style={{ fontSize: 11, color: 'var(--text-faint)' }}>
                {value.length} selected{max ? ` / ${max}` : ''}
              </span>
              <div style={{ flex: 1 }} />
              {value.length > 0 && (
                <button
                  type="button"
                  className="btn btn-subtle btn-sm"
                  onClick={() => onChange?.([])}
                >
                  Clear
                </button>
              )}
            </div>
          }
        />
      </SelPanel>
    </>
  );
}

/* ---------------- TokenInput (creatable tags) ---------------- */

export interface TokenInputProps {
  value?: string[];
  onChange?: (value: string[]) => void;
  placeholder?: string;
}

export function TokenInput({
  value = [],
  onChange,
  placeholder = 'Type and press Enter…',
}: TokenInputProps) {
  const [draft, setDraft] = useState('');
  const add = () => {
    const t = draft.trim();
    if (t && !value.includes(t)) onChange?.([...value, t]);
    setDraft('');
  };
  const onKey = (e: ReactKeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      add();
    } else if (e.key === 'Backspace' && !draft && value.length) {
      onChange?.(value.slice(0, -1));
    }
  };
  return (
    <div
      className="ui-trigger"
      style={{
        cursor: 'text',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 6,
        paddingTop: 5,
        paddingBottom: 5,
      }}
      onClick={(e) => e.currentTarget.querySelector('input')?.focus()}
    >
      {value.map((t) => (
        <span key={t} className="ui-tag" style={{ maxWidth: '100%' }}>
          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {t}
          </span>
          <button
            type="button"
            onClick={() => onChange?.(value.filter((v) => v !== t))}
            aria-label={`Remove ${t}`}
          >
            <Icon.x style={{ width: 11, height: 11 }} />
          </button>
        </span>
      ))}
      <input
        value={draft}
        placeholder={value.length ? '' : placeholder}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={onKey}
        onBlur={add}
        style={{
          flex: '1 1 80px',
          minWidth: 80,
          border: 0,
          background: 'transparent',
          outline: 'none',
          font: 'inherit',
          fontSize: 13.5,
          color: 'var(--text)',
        }}
      />
    </div>
  );
}

// packages/angular/src/select.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';

export type SelectValue = string | number;
export interface SelectOption {
  value: SelectValue;
  label: string;
  /** Optional color swatch shown before the label. */
  swatch?: string;
}
export type SelectOptionInput = SelectValue | SelectOption;

function normalize(o: SelectOptionInput): SelectOption {
  return typeof o === 'object' ? o : { value: o, label: String(o) };
}

/* ---------------- anchored, in-place floating panel ---------------- */

/**
 * Floating panel that tracks its trigger. Renders in place — `.ui-menu` is
 * positioned `fixed` from the anchor's rect, so it escapes overflow as long as
 * the component lives inside `.vsp-root`. Project the panel body as content.
 */
@Component({
  selector: 'vsp-sel-panel',
  template: `@if (open && rect) {
    <div
      #panel
      class="ui-menu ui-combo"
      style="position: fixed; z-index: 330"
      [style.top.px]="rect.bottom + 6"
      [style.left.px]="rect.left"
      [style.width.px]="width ?? rect.width"
      [style.maxHeight.px]="maxH"
    >
      <ng-content />
    </div>
  }`,
})
export class VspSelPanel implements OnChanges, OnDestroy {
  @Input() open = false;
  @Input() anchor: HTMLElement | null = null;
  @Input() width?: number;
  @Output() close = new EventEmitter<void>();
  @ViewChild('panel') panel?: ElementRef<HTMLElement>;

  rect: DOMRect | null = null;
  private cleanup: (() => void) | null = null;

  get maxH(): number {
    return Math.max(220, window.innerHeight - (this.rect?.bottom ?? 0) - 16);
  }

  private place = (): void => {
    if (this.anchor) this.rect = this.anchor.getBoundingClientRect();
  };

  ngOnChanges(c: SimpleChanges): void {
    if (c['open']) {
      if (this.open) this.activate();
      else this.deactivate();
    }
  }

  private activate(): void {
    this.place();
    const onDoc = (e: MouseEvent): void => {
      const t = e.target as Node;
      if (!this.panel?.nativeElement.contains(t) && !this.anchor?.contains(t)) this.close.emit();
    };
    const onEsc = (e: KeyboardEvent): void => {
      if (e.key === 'Escape') this.close.emit();
    };
    document.addEventListener('mousedown', onDoc);
    window.addEventListener('keydown', onEsc);
    window.addEventListener('resize', this.place);
    window.addEventListener('scroll', this.place, true);
    this.cleanup = () => {
      document.removeEventListener('mousedown', onDoc);
      window.removeEventListener('keydown', onEsc);
      window.removeEventListener('resize', this.place);
      window.removeEventListener('scroll', this.place, true);
    };
  }

  private deactivate(): void {
    this.cleanup?.();
    this.cleanup = null;
    this.rect = null;
  }

  ngOnDestroy(): void {
    this.cleanup?.();
  }
}

/* ---------------- search + list ---------------- */

@Component({
  selector: 'vsp-combo-list',
  template: `
    <div class="ui-combo-search">
      <svg
        viewBox="0 0 24 24"
        width="16"
        height="16"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="11" cy="11" r="7" />
        <path d="m21 21-4.3-4.3" />
      </svg>
      <input
        #search
        [value]="q"
        [placeholder]="searchPlaceholder ?? 'Search…'"
        (input)="onInput($event)"
        (keydown)="onKey($event)"
      />
    </div>
    <div class="ui-combo-list">
      @if (items.length === 0) {
        <div class="ui-combo-empty">No matches for “{{ q }}”</div>
      }
      @for (o of items; track o.value; let i = $index) {
        <div
          [class]="'ui-combo-item' + (i === activeIdx ? ' active' : '')"
          (mouseenter)="activeIdxChange.emit(i)"
          (click)="pick.emit(o)"
        >
          @if (o.swatch) {
            <span
              [style.background]="o.swatch"
              style="width: 9px; height: 9px; border-radius: 3px; flex-shrink: 0"
            ></span>
          }
          <span>{{ o.label }}</span>
          @if (isSel(o)) {
            <svg
              class="tick"
              viewBox="0 0 24 24"
              width="14"
              height="14"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M20 6L9 17l-5-5" />
            </svg>
          }
        </div>
      }
    </div>
    <ng-content select="[footer]" />
  `,
})
export class VspComboList implements AfterViewInit {
  @Input() q = '';
  @Input() items: SelectOption[] = [];
  @Input() activeIdx = 0;
  @Input() isSel: (o: SelectOption) => boolean = () => false;
  @Input() searchPlaceholder?: string;
  @Output() qChange = new EventEmitter<string>();
  @Output() activeIdxChange = new EventEmitter<number>();
  @Output() pick = new EventEmitter<SelectOption>();
  @ViewChild('search') search?: ElementRef<HTMLInputElement>;

  ngAfterViewInit(): void {
    setTimeout(() => this.search?.nativeElement.focus(), 30);
  }

  onInput(e: Event): void {
    this.qChange.emit((e.target as HTMLInputElement).value);
    this.activeIdxChange.emit(0);
  }

  onKey(e: KeyboardEvent): void {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      this.activeIdxChange.emit(Math.min(this.items.length - 1, this.activeIdx + 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      this.activeIdxChange.emit(Math.max(0, this.activeIdx - 1));
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const it = this.items[this.activeIdx];
      if (it) this.pick.emit(it);
    }
  }
}

/* ---------------- Select (themed drop-in, auto-searches at ≥8 options) ---------------- */

@Component({
  selector: 'vsp-select',
  imports: [VspSelPanel, VspComboList],
  template: `
    <button
      #anchor
      type="button"
      [disabled]="disabled"
      [class]="'ui-selectbtn' + (open ? ' open' : '')"
      (click)="open = !open"
    >
      <span [class]="'val' + (sel ? '' : ' ph')">{{ sel ? sel.label : placeholder }}</span>
    </button>
    <vsp-sel-panel [open]="open" [anchor]="anchor" (close)="open = false">
      @if (open) {
        @if (useSearch) {
          <vsp-combo-list
            [q]="q"
            [items]="items"
            [activeIdx]="active"
            [isSel]="isSelFn"
            (qChange)="q = $event"
            (activeIdxChange)="active = $event"
            (pick)="choose($event)"
          />
        } @else {
          <div class="ui-combo-list">
            @if (items.length === 0) {
              <div class="ui-combo-empty">No options</div>
            }
            @for (o of items; track o.value) {
              <div [class]="'ui-combo-item' + (sameVal(o) ? ' active' : '')" (click)="choose(o)">
                @if (o.swatch) {
                  <span
                    [style.background]="o.swatch"
                    style="width: 9px; height: 9px; border-radius: 3px; flex-shrink: 0"
                  ></span>
                }
                <span>{{ o.label }}</span>
                @if (sameVal(o)) {
                  <svg
                    class="tick"
                    viewBox="0 0 24 24"
                    width="14"
                    height="14"
                    fill="none"
                    stroke="currentColor"
                    stroke-width="2"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path d="M20 6L9 17l-5-5" />
                  </svg>
                }
              </div>
            }
          </div>
        }
      }
    </vsp-sel-panel>
  `,
})
export class VspSelect {
  @Input() options: SelectOptionInput[] = [];
  @Input() value?: SelectValue;
  @Output() valueChange = new EventEmitter<SelectValue>();
  @Input() placeholder = 'Select…';
  @Input() disabled = false;
  @Input() searchable?: boolean;

  open = false;
  q = '';
  active = 0;

  get opts(): SelectOption[] {
    return this.options.map(normalize);
  }
  get cur(): SelectValue | undefined {
    return this.value ?? this.opts[0]?.value;
  }
  get sel(): SelectOption | undefined {
    return this.opts.find((o) => String(o.value) === String(this.cur));
  }
  get useSearch(): boolean {
    return this.searchable ?? this.opts.length >= 8;
  }
  get items(): SelectOption[] {
    return this.useSearch
      ? this.opts.filter((o) => o.label.toLowerCase().includes(this.q.toLowerCase()))
      : this.opts;
  }
  isSelFn = (o: SelectOption): boolean => String(o.value) === String(this.cur);
  sameVal(o: SelectOption): boolean {
    return String(o.value) === String(this.cur);
  }
  choose(o: SelectOption): void {
    this.value = o.value;
    this.valueChange.emit(o.value);
    this.open = false;
    this.q = '';
  }
}

/* ---------------- Combobox (searchable single select) ---------------- */

@Component({
  selector: 'vsp-combobox',
  imports: [VspSelPanel, VspComboList],
  template: `
    <button
      #anchor
      type="button"
      [class]="'ui-trigger' + (open ? ' open' : '')"
      (click)="open = !open"
    >
      <span [class]="'val' + (sel ? '' : ' ph')">{{ sel ? sel.label : placeholder }}</span>
      @if (clearable && sel) {
        <span
          role="button"
          tabindex="-1"
          style="display: grid; place-items: center; color: var(--text-faint)"
          (click)="clear($event)"
          (keydown.enter)="set(null)"
        >
          <svg
            viewBox="0 0 24 24"
            width="14"
            height="14"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </span>
      }
      <svg
        class="chev"
        viewBox="0 0 24 24"
        width="16"
        height="16"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M6 9l6 6 6-6" />
      </svg>
    </button>
    <vsp-sel-panel [open]="open" [anchor]="anchor" (close)="open = false">
      @if (open) {
        <vsp-combo-list
          [q]="q"
          [items]="items"
          [activeIdx]="active"
          [isSel]="isSelFn"
          [searchPlaceholder]="searchPlaceholder"
          (qChange)="q = $event"
          (activeIdxChange)="active = $event"
          (pick)="pick($event)"
        />
      }
    </vsp-sel-panel>
  `,
})
export class VspCombobox {
  @Input() options: SelectOptionInput[] = [];
  @Input() value: SelectValue | null = null;
  @Output() valueChange = new EventEmitter<SelectValue | null>();
  @Input() placeholder = 'Select…';
  @Input() searchPlaceholder?: string;
  @Input() clearable = false;

  open = false;
  q = '';
  active = 0;

  get opts(): SelectOption[] {
    return this.options.map(normalize);
  }
  get sel(): SelectOption | undefined {
    return this.opts.find((o) => o.value === this.value);
  }
  get items(): SelectOption[] {
    return this.opts.filter((o) => o.label.toLowerCase().includes(this.q.toLowerCase()));
  }
  isSelFn = (o: SelectOption): boolean => o.value === this.value;
  set(v: SelectValue | null): void {
    this.value = v;
    this.valueChange.emit(v);
  }
  clear(e: Event): void {
    e.stopPropagation();
    this.set(null);
  }
  pick(o: SelectOption): void {
    this.set(o.value);
    this.open = false;
    this.q = '';
  }
}

/* ---------------- MultiSelect (searchable, tagged) ---------------- */

@Component({
  selector: 'vsp-multi-select',
  imports: [VspSelPanel, VspComboList],
  template: `
    <div
      #anchor
      role="button"
      tabindex="0"
      [class]="'ui-trigger' + (open ? ' open' : '')"
      style="min-height: var(--ctrl-h)"
      (click)="open = !open"
      (keydown.enter)="toggleOpen($event)"
      (keydown.space)="toggleOpen($event)"
    >
      @if (selOpts.length === 0) {
        <span class="val ph">{{ placeholder }}</span>
      } @else {
        <span class="tags">
          @for (o of selOpts; track o.value) {
            <span class="ui-tag" (click)="$event.stopPropagation()">
              {{ o.label }}
              <button type="button" [attr.aria-label]="'Remove ' + o.label" (click)="remove(o)">
                <svg
                  viewBox="0 0 24 24"
                  width="11"
                  height="11"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path d="M18 6L6 18M6 6l12 12" />
                </svg>
              </button>
            </span>
          }
        </span>
      }
      <svg
        class="chev"
        viewBox="0 0 24 24"
        width="16"
        height="16"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <path d="M6 9l6 6 6-6" />
      </svg>
    </div>
    <vsp-sel-panel [open]="open" [anchor]="anchor" (close)="open = false">
      @if (open) {
        <vsp-combo-list
          [q]="q"
          [items]="items"
          [activeIdx]="active"
          [isSel]="isSelFn"
          [searchPlaceholder]="searchPlaceholder"
          (qChange)="q = $event"
          (activeIdxChange)="active = $event"
          (pick)="toggle($event)"
        >
          <div footer class="ui-combo-foot">
            <span class="mono" style="font-size: 11px; color: var(--text-faint)">
              {{ value.length }} selected{{ max ? ' / ' + max : '' }}
            </span>
            <div style="flex: 1"></div>
            @if (value.length > 0) {
              <button type="button" class="btn btn-subtle btn-sm" (click)="set([])">Clear</button>
            }
          </div>
        </vsp-combo-list>
      }
    </vsp-sel-panel>
  `,
})
export class VspMultiSelect {
  @Input() options: SelectOptionInput[] = [];
  @Input() value: SelectValue[] = [];
  @Output() valueChange = new EventEmitter<SelectValue[]>();
  @Input() placeholder = 'Select…';
  @Input() searchPlaceholder?: string;
  @Input() max?: number;

  open = false;
  q = '';
  active = 0;

  get opts(): SelectOption[] {
    return this.options.map(normalize);
  }
  get items(): SelectOption[] {
    return this.opts.filter((o) => o.label.toLowerCase().includes(this.q.toLowerCase()));
  }
  get selOpts(): SelectOption[] {
    return this.opts.filter((o) => this.has(o.value));
  }
  has(v: SelectValue): boolean {
    return this.value.includes(v);
  }
  isSelFn = (o: SelectOption): boolean => this.has(o.value);
  set(next: SelectValue[]): void {
    this.value = next;
    this.valueChange.emit(next);
  }
  toggle(o: SelectOption): void {
    if (this.has(o.value)) this.set(this.value.filter((v) => v !== o.value));
    else if (!this.max || this.value.length < this.max) this.set([...this.value, o.value]);
  }
  remove(o: SelectOption): void {
    this.set(this.value.filter((v) => v !== o.value));
  }
  toggleOpen(e: Event): void {
    e.preventDefault();
    this.open = !this.open;
  }
}

/* ---------------- TokenInput (creatable tags) ---------------- */

@Component({
  selector: 'vsp-token-input',
  template: `
    <div
      #root
      class="ui-trigger"
      style="cursor: text; flex-wrap: wrap; align-items: center; gap: 6px; padding-top: 5px; padding-bottom: 5px"
      (click)="focusInput()"
    >
      @for (t of value; track t) {
        <span class="ui-tag" style="max-width: 100%">
          <span style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{
            t
          }}</span>
          <button type="button" [attr.aria-label]="'Remove ' + t" (click)="remove(t)">
            <svg
              viewBox="0 0 24 24"
              width="11"
              height="11"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </span>
      }
      <input
        [value]="draft"
        [placeholder]="value.length ? '' : placeholder"
        (input)="draft = $any($event.target).value"
        (keydown)="onKey($event)"
        (blur)="add()"
        style="flex: 1 1 80px; min-width: 80px; border: 0; background: transparent; outline: none; font: inherit; font-size: 13.5px; color: var(--text)"
      />
    </div>
  `,
})
export class VspTokenInput {
  @Input() value: string[] = [];
  @Output() valueChange = new EventEmitter<string[]>();
  @Input() placeholder = 'Type and press Enter…';
  @ViewChild('root') root?: ElementRef<HTMLElement>;

  draft = '';

  set(next: string[]): void {
    this.value = next;
    this.valueChange.emit(next);
  }
  add(): void {
    const t = this.draft.trim();
    if (t && !this.value.includes(t)) this.set([...this.value, t]);
    this.draft = '';
  }
  remove(t: string): void {
    this.set(this.value.filter((v) => v !== t));
  }
  focusInput(): void {
    this.root?.nativeElement.querySelector('input')?.focus();
  }
  onKey(e: KeyboardEvent): void {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      this.add();
    } else if (e.key === 'Backspace' && !this.draft && this.value.length) {
      this.set(this.value.slice(0, -1));
    }
  }
}
