// packages/react/src/Anchored.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { getPortalTarget } from './portal';
import { cx } from './cx';

export type AnchoredAlign = 'start' | 'end';

export interface AnchoredProps {
  trigger: ReactNode;
  children: ReactNode | ((close: () => void) => ReactNode);
  align?: AnchoredAlign;
  width?: number;
  className?: string;
}

/** Positioning base for menus and popovers: anchors a portaled layer to a trigger. */
export function Anchored({
  trigger,
  children,
  align = 'start',
  width,
  className = 'ui-menu',
}: AnchoredProps) {
  const [open, setOpen] = useState(false);
  const [rect, setRect] = useState<DOMRect | null>(null);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const layerRef = useRef<HTMLDivElement>(null);

  const place = useCallback(() => {
    if (triggerRef.current) setRect(triggerRef.current.getBoundingClientRect());
  }, []);

  useLayoutEffect(() => {
    if (open) place();
  }, [open, place]);

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      const t = e.target as Node;
      if (!layerRef.current?.contains(t) && !triggerRef.current?.contains(t)) setOpen(false);
    };
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    const scroller = document.querySelector('.vsp-content');
    document.addEventListener('mousedown', onDoc);
    window.addEventListener('keydown', onEsc);
    window.addEventListener('resize', place);
    scroller?.addEventListener('scroll', place, true);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      window.removeEventListener('keydown', onEsc);
      window.removeEventListener('resize', place);
      scroller?.removeEventListener('scroll', place, true);
    };
  }, [open, place]);

  let style: CSSProperties = {};
  if (rect) {
    style = { position: 'fixed', top: rect.bottom + 6, minWidth: width ?? rect.width, zIndex: 320 };
    if (align === 'end') style.right = window.innerWidth - rect.right;
    else style.left = rect.left;
  }

  const target = open && rect ? getPortalTarget() : null;

  return (
    <>
      <span ref={triggerRef} onClick={() => setOpen((o) => !o)} style={{ display: 'inline-flex' }}>
        {trigger}
      </span>
      {target &&
        createPortal(
          <div ref={layerRef} className={className} style={style}>
            {typeof children === 'function' ? children(() => setOpen(false)) : children}
          </div>,
          target,
        )}
    </>
  );
}

export interface MenuItem {
  label?: ReactNode;
  icon?: ReactNode;
  kbd?: ReactNode;
  danger?: boolean;
  heading?: boolean;
  sep?: boolean;
  onClick?: () => void;
}

export interface DropdownMenuProps {
  trigger: ReactNode;
  items: MenuItem[];
  align?: AnchoredAlign;
  width?: number;
}

export function DropdownMenu({ trigger, items, align = 'end', width }: DropdownMenuProps) {
  return (
    <Anchored trigger={trigger} align={align} width={width}>
      {(close) =>
        items.map((it, i) => {
          if (it.sep) return <div key={i} className="ui-menu-sep" />;
          if (it.heading)
            return (
              <div key={i} className="ui-menu-label">
                {it.label}
              </div>
            );
          return (
            <button
              key={i}
              type="button"
              className={cx('ui-menu-item', it.danger && 'danger')}
              onClick={() => {
                it.onClick?.();
                close();
              }}
            >
              {it.icon}
              {it.label}
              {it.kbd && <kbd className="ui-kbd">{it.kbd}</kbd>}
            </button>
          );
        })
      }
    </Anchored>
  );
}

export interface PopoverProps {
  trigger: ReactNode;
  children: ReactNode;
  align?: AnchoredAlign;
  width?: number;
}

export function Popover({ trigger, children, align = 'start', width = 260 }: PopoverProps) {
  return (
    <Anchored trigger={trigger} align={align} width={width} className="ui-popover">
      {children}
    </Anchored>
  );
}

// packages/svelte/src/Anchored.svelte
<script>
  import { portal } from './portal.js';
  let { align = 'start', width, layerClass = 'ui-menu', trigger, children } = $props();
  let open = $state(false);
  let rect = $state(null);
  let triggerEl = $state();
  let layerEl = $state();
  const place = () => {
    if (triggerEl) rect = triggerEl.getBoundingClientRect();
  };
  const close = () => (open = false);
  const toggle = () => {
    open = !open;
    if (open) requestAnimationFrame(place);
  };
  $effect(() => {
    if (!open) return;
    place();
    const onDoc = (e) => {
      if (!layerEl?.contains(e.target) && !triggerEl?.contains(e.target)) close();
    };
    const onEsc = (e) => {
      if (e.key === 'Escape') close();
    };
    document.addEventListener('mousedown', onDoc);
    window.addEventListener('keydown', onEsc);
    window.addEventListener('resize', place);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      window.removeEventListener('keydown', onEsc);
      window.removeEventListener('resize', place);
    };
  });
  let style = $derived.by(() => {
    if (!rect) return '';
    let s = `position:fixed;top:${rect.bottom + 6}px;min-width:${width ?? rect.width}px;z-index:320;`;
    s += align === 'end' ? `right:${window.innerWidth - rect.right}px` : `left:${rect.left}px`;
    return s;
  });
</script>

<span
  bind:this={triggerEl}
  role="button"
  tabindex="0"
  onclick={toggle}
  onkeydown={(e) => {
    if (e.key === 'Enter' || e.key === ' ') toggle();
  }}
  style="display:inline-flex">{@render trigger?.()}</span
>

{#if open && rect}
  <div bind:this={layerEl} use:portal class={layerClass} {style}>
    {@render children?.(close)}
  </div>
{/if}
