// packages/react/src/Tabs.tsx
import type { ReactNode } from 'react';
import { cx } from './cx';

export type TabItem =
  | string
  | { value: string; label: ReactNode; count?: number; disabled?: boolean };

export interface TabsProps {
  tabs: TabItem[];
  value: string;
  onChange: (value: string) => void;
  right?: ReactNode;
}

export function Tabs({ tabs, value, onChange, right }: TabsProps) {
  return (
    <div className="ui-tabs" style={{ alignItems: 'center' }}>
      {tabs.map((t) => {
        const id = typeof t === 'string' ? t : t.value;
        const label = typeof t === 'string' ? t : t.label;
        const count = typeof t === 'object' ? t.count : undefined;
        const disabled = typeof t === 'object' ? t.disabled : undefined;
        return (
          <button
            key={id}
            type="button"
            disabled={disabled}
            className={cx('ui-tab', value === id && 'on')}
            onClick={() => onChange(id)}
          >
            {label}
            {count != null && (
              <span className="badge badge-muted" style={{ marginLeft: 7 }}>
                {count}
              </span>
            )}
          </button>
        );
      })}
      {right && (
        <>
          <div style={{ flex: 1 }} />
          {right}
        </>
      )}
    </div>
  );
}

// packages/svelte/src/Tabs.svelte
<script>
  let { value = $bindable(), tabs = [], right } = $props();
  const id = (t) => (typeof t === 'string' ? t : t.value);
  const lbl = (t) => (typeof t === 'string' ? t : t.label);
  const cnt = (t) => (typeof t === 'object' ? t.count : undefined);
  const dis = (t) => (typeof t === 'object' ? t.disabled : undefined);
</script>

<div class="ui-tabs" style="align-items:center">
  {#each tabs as t (id(t))}
    <button
      type="button"
      disabled={dis(t)}
      class="ui-tab{value === id(t) ? ' on' : ''}"
      onclick={() => (value = id(t))}
    >
      {lbl(t)}{#if cnt(t) != null}<span class="badge badge-muted" style="margin-left:7px"
          >{cnt(t)}</span
        >{/if}
    </button>
  {/each}
  {#if right}<div style="flex:1"></div>{@render right()}{/if}
</div>
