// packages/angular/src/anchored.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import { VspIcon } from './icon.component';

export type AnchoredAlign = 'start' | 'end';

/**
 * Positioning base for menus and popovers: anchors a layer to a trigger. The
 * layer is `position: fixed`, so it renders in place (inside `.vsp-root`) and is
 * positioned against the trigger's viewport rect. Click-outside and Escape close
 * it. Project the trigger with `slot="trigger"`; the default slot is the layer.
 */
@Component({
  selector: 'vsp-anchored',
  template: `<span #trig style="display: inline-flex" (click)="toggle()">
      <ng-content select="[slot=trigger]" />
    </span>
    @if (isOpen) {
      <div #layer [class]="layerClass" [style]="layerStyle"><ng-content /></div>
    }`,
})
export class VspAnchored {
  @Input() align: AnchoredAlign = 'start';
  @Input() width?: number;
  @Input() layerClass = 'ui-menu';
  /** Controlled open state. Leave unset for uncontrolled. */
  @Input('open') openInput?: boolean;
  @Output() openChange = new EventEmitter<boolean>();
  @ViewChild('trig') trig!: ElementRef<HTMLElement>;
  @ViewChild('layer') layer?: ElementRef<HTMLElement>;
  internalOpen = false;
  rect: DOMRect | null = null;

  get isOpen(): boolean {
    return this.openInput !== undefined ? this.openInput : this.internalOpen;
  }
  private setOpen(next: boolean): void {
    if (this.openInput === undefined) this.internalOpen = next;
    this.openChange.emit(next);
  }
  toggle(): void {
    const next = !this.isOpen;
    this.setOpen(next);
    if (next) requestAnimationFrame(() => this.place());
  }
  close(): void {
    this.setOpen(false);
  }
  place(): void {
    if (this.trig) this.rect = this.trig.nativeElement.getBoundingClientRect();
  }
  get layerStyle(): string {
    const r = this.rect;
    if (!r) return '';
    let s = `position:fixed;top:${r.bottom + 6}px;min-width:${this.width ?? r.width}px;z-index:320;`;
    s += this.align === 'end' ? `right:${window.innerWidth - r.right}px` : `left:${r.left}px`;
    return s;
  }
  @HostListener('document:mousedown', ['$event'])
  onDoc(e: MouseEvent): void {
    if (!this.isOpen) return;
    const t = e.target as Node;
    if (!this.layer?.nativeElement.contains(t) && !this.trig?.nativeElement.contains(t))
      this.close();
  }
  @HostListener('document:keydown.escape')
  onEsc(): void {
    if (this.isOpen) this.close();
  }
  @HostListener('window:resize')
  onResize(): void {
    if (this.isOpen) this.place();
  }
}

export interface MenuItem {
  label?: string;
  kbd?: string;
  /** Optional leading icon name (see `vsp-icon`). */
  icon?: string;
  danger?: boolean;
  heading?: boolean;
  sep?: boolean;
  disabled?: boolean;
  /** Render as a checkable item — shows a tick and keeps the menu open on select. */
  type?: 'checkbox' | 'radio';
  checked?: boolean;
  onClick?: () => void;
}

@Component({
  selector: 'vsp-dropdown-menu',
  imports: [VspAnchored, VspIcon],
  template: `<vsp-anchored
    #a
    [align]="align"
    [width]="width"
    [open]="open"
    (openChange)="openChange.emit($event)"
    layerClass="ui-menu"
  >
    <span slot="trigger"><ng-content select="[slot=trigger]" /></span>
    @for (it of items; track $index) {
      @if (it.sep) {
        <div class="ui-menu-sep"></div>
      } @else if (it.heading) {
        <div class="ui-menu-label">{{ it.label }}</div>
      } @else {
        <button
          type="button"
          [class]="itemCls(it)"
          [attr.role]="role(it)"
          [disabled]="it.disabled"
          [attr.aria-checked]="it.type ? !!it.checked : null"
          (click)="select(it, a)"
          (keydown)="onKey($event)"
        >
          @if (it.type) {
            <span class="ui-menu-check">
              @if (it.checked) {
                <vsp-icon name="check" [size]="16" />
              }
            </span>
          } @else if (it.icon) {
            <vsp-icon [name]="it.icon" [size]="15" />
          }
          {{ it.label }}
          @if (it.kbd) {
            <kbd class="ui-kbd">{{ it.kbd }}</kbd>
          }
        </button>
      }
    }
  </vsp-anchored>`,
})
export class VspDropdownMenu {
  @Input() items: MenuItem[] = [];
  @Input() align: AnchoredAlign = 'end';
  @Input() width?: number;
  @Input() open?: boolean;
  @Output() openChange = new EventEmitter<boolean>();
  role(it: MenuItem): string {
    return it.type === 'checkbox'
      ? 'menuitemcheckbox'
      : it.type === 'radio'
        ? 'menuitemradio'
        : 'menuitem';
  }
  select(it: MenuItem, a: VspAnchored): void {
    it.onClick?.();
    if (!it.type) a.close();
  }
  onKey(e: KeyboardEvent): void {
    const k = e.key;
    if (k !== 'ArrowDown' && k !== 'ArrowUp' && k !== 'Home' && k !== 'End') return;
    e.preventDefault();
    const parent = (e.currentTarget as HTMLElement).parentElement;
    if (!parent) return;
    const els = Array.from(
      parent.querySelectorAll<HTMLButtonElement>('[role^="menuitem"]:not([disabled])'),
    );
    const i = els.indexOf(e.currentTarget as HTMLButtonElement);
    const n = els.length;
    const next =
      k === 'Home'
        ? els[0]
        : k === 'End'
          ? els[n - 1]
          : k === 'ArrowDown'
            ? els[(i + 1) % n]
            : els[(i - 1 + n) % n];
    next?.focus();
  }
  itemCls(it: MenuItem): string {
    return 'ui-menu-item' + (it.danger ? ' danger' : '');
  }
}

@Component({
  selector: 'vsp-popover',
  imports: [VspAnchored],
  template: `<vsp-anchored
    [align]="align"
    [width]="width"
    [open]="open"
    (openChange)="openChange.emit($event)"
    layerClass="ui-popover"
  >
    <span slot="trigger"><ng-content select="[slot=trigger]" /></span>
    <ng-content />
  </vsp-anchored>`,
})
export class VspPopover {
  @Input() align: AnchoredAlign = 'start';
  @Input() width = 260;
  @Input() open?: boolean;
  @Output() openChange = new EventEmitter<boolean>();
}

// packages/react/src/Anchored.tsx
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react';
import { createPortal } from 'react-dom';
import { Icon } from '@vespera-ui/icons';
import { getPortalTarget } from './portal';
import { cx } from './cx';

export type AnchoredAlign = 'start' | 'end';

export interface AnchoredProps {
  trigger: ReactNode;
  children: ReactNode | ((close: () => void) => ReactNode);
  align?: AnchoredAlign;
  width?: number;
  className?: string;
  /** Controlled open state. Omit for uncontrolled (the default). */
  open?: boolean;
  /** Notified whenever the open state should change (both modes). */
  onOpenChange?: (open: boolean) => void;
}

/** Positioning base for menus and popovers: anchors a portaled layer to a trigger. */
export function Anchored({
  trigger,
  children,
  align = 'start',
  width,
  className = 'ui-menu',
  open: openProp,
  onOpenChange,
}: AnchoredProps) {
  const controlled = openProp !== undefined;
  const [internalOpen, setInternalOpen] = useState(false);
  const open = controlled ? openProp : internalOpen;
  const setOpen = useCallback(
    (next: boolean) => {
      if (!controlled) setInternalOpen(next);
      onOpenChange?.(next);
    },
    [controlled, onOpenChange],
  );
  const [rect, setRect] = useState<DOMRect | null>(null);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const layerRef = useRef<HTMLDivElement>(null);

  const place = useCallback(() => {
    if (triggerRef.current) setRect(triggerRef.current.getBoundingClientRect());
  }, []);

  useLayoutEffect(() => {
    if (open) place();
  }, [open, place]);

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      const t = e.target as Node;
      if (!layerRef.current?.contains(t) && !triggerRef.current?.contains(t)) setOpen(false);
    };
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };
    const scroller = document.querySelector('.vsp-content');
    document.addEventListener('mousedown', onDoc);
    window.addEventListener('keydown', onEsc);
    window.addEventListener('resize', place);
    scroller?.addEventListener('scroll', place, true);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      window.removeEventListener('keydown', onEsc);
      window.removeEventListener('resize', place);
      scroller?.removeEventListener('scroll', place, true);
    };
  }, [open, place]);

  let style: CSSProperties = {};
  if (rect) {
    style = { position: 'fixed', top: rect.bottom + 6, minWidth: width ?? rect.width, zIndex: 320 };
    if (align === 'end') style.right = window.innerWidth - rect.right;
    else style.left = rect.left;
  }

  const target = open && rect ? getPortalTarget() : null;

  return (
    <>
      <span ref={triggerRef} onClick={() => setOpen(!open)} style={{ display: 'inline-flex' }}>
        {trigger}
      </span>
      {target &&
        createPortal(
          <div ref={layerRef} className={className} style={style}>
            {typeof children === 'function' ? children(() => setOpen(false)) : children}
          </div>,
          target,
        )}
    </>
  );
}

export interface MenuItem {
  label?: ReactNode;
  icon?: ReactNode;
  kbd?: ReactNode;
  danger?: boolean;
  heading?: boolean;
  sep?: boolean;
  disabled?: boolean;
  /** Render as a checkable item — shows a tick and keeps the menu open on select. */
  type?: 'checkbox' | 'radio';
  checked?: boolean;
  onClick?: () => void;
}

/** Roving arrow-key focus between menu items. */
function onMenuKey(e: import('react').KeyboardEvent<HTMLButtonElement>) {
  const key = e.key;
  if (key !== 'ArrowDown' && key !== 'ArrowUp' && key !== 'Home' && key !== 'End') return;
  e.preventDefault();
  const parent = e.currentTarget.parentElement;
  if (!parent) return;
  const items = Array.from(
    parent.querySelectorAll<HTMLButtonElement>('[role^="menuitem"]:not([disabled])'),
  );
  const i = items.indexOf(e.currentTarget);
  const next =
    key === 'Home'
      ? items[0]
      : key === 'End'
        ? items[items.length - 1]
        : key === 'ArrowDown'
          ? items[(i + 1) % items.length]
          : items[(i - 1 + items.length) % items.length];
  next?.focus();
}

export interface DropdownMenuProps {
  trigger: ReactNode;
  items: MenuItem[];
  align?: AnchoredAlign;
  width?: number;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function DropdownMenu({
  trigger,
  items,
  align = 'end',
  width,
  open,
  onOpenChange,
}: DropdownMenuProps) {
  return (
    <Anchored trigger={trigger} align={align} width={width} open={open} onOpenChange={onOpenChange}>
      {(close) =>
        items.map((it, i) => {
          if (it.sep) return <div key={i} className="ui-menu-sep" />;
          if (it.heading)
            return (
              <div key={i} className="ui-menu-label">
                {it.label}
              </div>
            );
          const role =
            it.type === 'checkbox'
              ? 'menuitemcheckbox'
              : it.type === 'radio'
                ? 'menuitemradio'
                : 'menuitem';
          return (
            <button
              key={i}
              type="button"
              role={role}
              disabled={it.disabled}
              aria-checked={it.type ? !!it.checked : undefined}
              className={cx('ui-menu-item', it.danger && 'danger')}
              onClick={() => {
                it.onClick?.();
                if (!it.type) close();
              }}
              onKeyDown={onMenuKey}
            >
              {it.type ? (
                <span className="ui-menu-check">{it.checked && <Icon.check />}</span>
              ) : (
                it.icon
              )}
              {it.label}
              {it.kbd && <kbd className="ui-kbd">{it.kbd}</kbd>}
            </button>
          );
        })
      }
    </Anchored>
  );
}

export interface PopoverProps {
  trigger: ReactNode;
  children: ReactNode;
  align?: AnchoredAlign;
  width?: number;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}

export function Popover({
  trigger,
  children,
  align = 'start',
  width = 260,
  open,
  onOpenChange,
}: PopoverProps) {
  return (
    <Anchored
      trigger={trigger}
      align={align}
      width={width}
      className="ui-popover"
      open={open}
      onOpenChange={onOpenChange}
    >
      {children}
    </Anchored>
  );
}
