// packages/angular/src/button.component.ts
import { Component, Input } from '@angular/core';

export type ButtonVariant = 'primary' | 'ghost' | 'subtle' | 'outline' | 'danger';

@Component({
  selector: 'vsp-button',
  template: `<button [class]="cls" [disabled]="disabled || loading">
    @if (loading) {
      <span class="ui-spinner" aria-hidden="true"></span>
    }
    <ng-content />
  </button>`,
})
export class VspButton {
  @Input() variant: ButtonVariant = 'ghost';
  @Input() size?: 'sm';
  @Input() loading = false;
  @Input() disabled = false;

  get cls(): string {
    return ['btn', `btn-${this.variant}`, this.size === 'sm' ? 'btn-sm' : '']
      .filter(Boolean)
      .join(' ');
  }
}

// packages/react/src/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import { cx } from './cx';

export type ButtonVariant = 'primary' | 'ghost' | 'subtle' | 'outline' | 'danger';

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: 'sm';
  leadingIcon?: ReactNode;
  trailingIcon?: ReactNode;
  loading?: boolean;
}

export function Button({
  variant = 'ghost',
  size,
  leadingIcon,
  trailingIcon,
  loading,
  children,
  className,
  disabled,
  type = 'button',
  ...rest
}: ButtonProps) {
  return (
    <button
      type={type}
      className={cx('btn', `btn-${variant}`, size === 'sm' && 'btn-sm', className)}
      disabled={disabled || loading}
      {...rest}
    >
      {loading ? <span className="ui-spinner" aria-hidden /> : leadingIcon}
      {children}
      {!loading && trailingIcon}
    </button>
  );
}

export interface IconButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  icon: ReactNode;
  /** Accessible label (also the tooltip). */
  label: string;
  dot?: boolean;
}

export function IconButton({
  icon,
  label,
  dot,
  className,
  type = 'button',
  ...rest
}: IconButtonProps) {
  return (
    <button
      type={type}
      className={cx('vsp-icon-btn', className)}
      title={label}
      aria-label={label}
      {...rest}
    >
      {icon}
      {dot && <span className="vsp-dot" />}
    </button>
  );
}
