// packages/angular/src/card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'vsp-card',
  template: `<div [class]="cls"><ng-content /></div>`,
})
export class VspCard {
  @Input() pad = false;
  get cls(): string {
    return this.pad ? 'card card-pad' : 'card';
  }
}

@Component({
  selector: 'vsp-card-head',
  template: `<div class="card-head">
    <div style="min-width: 0">
      <div class="ttl">{{ title }}</div>
      @if (desc) {
        <div class="eyebrow" style="margin-top: 3px">{{ desc }}</div>
      }
    </div>
    <div class="vsp-top-spacer"></div>
    <ng-content select="[slot=right]" />
  </div>`,
})
export class VspCardHead {
  @Input() title?: string;
  @Input() desc?: string;
}

// packages/react/src/Card.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { cx } from './cx';

export interface CardProps extends HTMLAttributes<HTMLDivElement> {
  /** Apply the standard content padding. */
  pad?: boolean;
}

export function Card({ pad, className, children, ...rest }: CardProps) {
  return (
    <div className={cx('card', pad && 'card-pad', className)} {...rest}>
      {children}
    </div>
  );
}

export interface CardHeadProps {
  title?: ReactNode;
  desc?: ReactNode;
  right?: ReactNode;
}

export function CardHead({ title, desc, right }: CardHeadProps) {
  return (
    <div className="card-head">
      <div style={{ minWidth: 0 }}>
        <h3>{title}</h3>
        {desc && (
          <div className="eyebrow" style={{ marginTop: 3 }}>
            {desc}
          </div>
        )}
      </div>
      {right && (
        <>
          <div className="vsp-top-spacer" />
          {right}
        </>
      )}
    </div>
  );
}
