// packages/svelte/src/Sheet.svelte
<script>
  import { portal } from './portal.js';
  let { open = false, title, desc, icon, footer, children, onclose } = $props();
  $effect(() => {
    if (!open) return;
    const onkey = (e) => {
      if (e.key === 'Escape') onclose?.();
    };
    window.addEventListener('keydown', onkey);
    return () => window.removeEventListener('keydown', onkey);
  });
</script>

{#if open}
  <div
    class="ui-overlay"
    use:portal
    role="presentation"
    onmousedown={(e) => {
      if (e.target === e.currentTarget) onclose?.();
    }}
  >
    <div class="ui-sheet" role="dialog" aria-modal="true">
      <div class="ui-sheet-head">
        {#if icon}<span
            style="width:38px;height:38px;border-radius:var(--r-sm);display:grid;place-items:center;background:color-mix(in oklab, var(--accent) 13%, transparent);color:var(--accent);flex-shrink:0"
            >{@render icon()}</span
          >{/if}
        <div style="flex:1;min-width:0">
          <div style="font-size:16px;font-weight:700;letter-spacing:-.01em">{title}</div>
          {#if desc}<div style="font-size:12.5px;color:var(--text-dim);margin-top:3px">
              {desc}
            </div>{/if}
        </div>
        <button
          type="button"
          class="vsp-icon-btn"
          style="border:0;background:transparent;width:32px;height:32px"
          aria-label="Close"
          onclick={() => onclose?.()}
        >
          <svg
            viewBox="0 0 24 24"
            width="16"
            height="16"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"><path d="M18 6L6 18M6 6l12 12" /></svg
          >
        </button>
      </div>
      <div class="ui-sheet-body vsp-scroll">{@render children?.()}</div>
      {#if footer}<div class="ui-sheet-foot">{@render footer()}</div>{/if}
    </div>
  </div>
{/if}

// packages/react/src/Sheet.tsx
import type { ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { Icon } from '@vespera-ui/icons';
import { getPortalTarget } from './portal';
import { useEsc } from './hooks';

export interface SheetProps {
  open: boolean;
  onClose?: () => void;
  title?: ReactNode;
  desc?: ReactNode;
  children?: ReactNode;
  footer?: ReactNode;
  icon?: ReactNode;
}

export function Sheet({ open, onClose, title, desc, children, footer, icon }: SheetProps) {
  useEsc(open, onClose);
  const target = open ? getPortalTarget() : null;
  if (!target) return null;

  return createPortal(
    <div
      className="ui-overlay"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose?.();
      }}
    >
      <div className="ui-sheet" role="dialog" aria-modal="true">
        <div className="ui-sheet-head">
          {icon && (
            <span
              style={{
                width: 38,
                height: 38,
                borderRadius: 'var(--r-sm)',
                display: 'grid',
                placeItems: 'center',
                background: 'color-mix(in oklab, var(--accent) 13%, transparent)',
                color: 'var(--accent)',
                flexShrink: 0,
              }}
            >
              {icon}
            </span>
          )}
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: '-.01em' }}>{title}</div>
            {desc && (
              <div style={{ fontSize: 12.5, color: 'var(--text-dim)', marginTop: 3 }}>{desc}</div>
            )}
          </div>
          <button
            type="button"
            className="vsp-icon-btn"
            style={{ border: 0, background: 'transparent', width: 32, height: 32 }}
            onClick={onClose}
            aria-label="Close"
          >
            <Icon.x />
          </button>
        </div>
        <div className="ui-sheet-body vsp-scroll">{children}</div>
        {footer && <div className="ui-sheet-foot">{footer}</div>}
      </div>
    </div>,
    target,
  );
}
